@extends('layouts.app')
@section('title', 'Caja')
@section('page-title', 'Tienda · Caja')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 fw-bold">Caja</h1><p class="text-secondary mb-0">Escaparate y venta en una sola pantalla.</p></div><a href="{{ route('store.sales') }}" class="btn btn-outline-primary"><i class="bi bi-receipt me-1"></i>Ventas</a></div>
<form method="POST" action="{{ route('store.sales.store') }}" data-cashier-form>@csrf
<div class="row g-4"><div class="col-lg-7"><div class="card border-0 shadow-sm"><div class="card-body"><div class="d-flex justify-content-between align-items-center gap-2 mb-3"><label class="form-label mb-0">Productos disponibles</label><button type="button" class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#productSearchModal"><i class="bi bi-search me-1"></i>Buscar otros productos</button></div><div class="row g-3" data-product-cards>@foreach($products as $product)<div class="col-md-6" data-product-card data-product-name="{{ strtolower($product->name.' '.$product->code) }}"><div class="border rounded p-3 h-100"><div class="d-flex justify-content-between gap-2"><div><strong>{{ $product->name }}</strong><div class="small text-secondary">{{ $product->type }} · {{ $product->presentation ?: 'Unidad' }}</div></div><span class="text-success small">{{ $product->store_quantity }} disponibles</span></div><div class="d-flex justify-content-between align-items-center mt-3"><strong class="text-primary">S/ {{ $product->sale_price }}</strong><div class="btn-group btn-group-sm"><button type="button" class="btn btn-outline-secondary" data-product-minus="{{ $product->id }}">−</button><span class="btn btn-light" data-product-quantity="{{ $product->id }}">0</span><button type="button" class="btn btn-primary" data-product-add="{{ $product->id }}">+</button></div></div><button type="button" class="btn btn-link btn-sm p-0 mt-2" data-product data-id="{{ $product->id }}" data-name="{{ $product->name }}" data-price="{{ $product->sale_price_cents }}" data-stock="{{ $product->store_quantity }}">Agregar rápidamente</button></div></div>@endforeach</div></div></div></div>
<div class="col-lg-5"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5">Venta actual</h2><div data-cart class="mb-3"><p class="text-muted">Agrega productos para iniciar la venta.</p></div><div class="border-top pt-3"><div class="d-flex justify-content-between fw-bold"><span>Total</span><span data-total>S/ 0.00</span></div></div><div class="mt-3"><label class="form-label">Comprador</label><select class="form-select" name="owner_id"><option value="">Cliente general</option>@foreach($owners as $owner)<option value="{{ $owner->id }}">{{ $owner->full_name }} · {{ $owner->dni }} · {{ $owner->phone }}</option>@endforeach</select></div><div class="mt-3"><label class="form-label">Método de pago</label><select class="form-select" name="payment_method"><option value="">No especificado</option><option value="EFECTIVO">Efectivo</option><option value="TARJETA">Tarjeta</option><option value="YAPE">Yape / Plin</option></select></div><button class="btn btn-primary w-100 mt-4" type="submit" disabled data-cashier-submit>Cobrar <span data-total-button>S/ 0.00</span></button></div></div></div></div></form>
<div class="modal fade" id="productSearchModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-5">Buscar otros productos</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body"><table class="table align-middle" data-datatable><thead><tr><th>Producto</th><th>Categoría</th><th>Precio</th><th>Stock Tienda</th><th>Acción</th></tr></thead><tbody>@foreach($products as $product)<tr><td>{{ $product->name }}</td><td>{{ $product->type }}</td><td>S/ {{ $product->sale_price }}</td><td>{{ $product->store_quantity }}</td><td><button type="button" class="btn btn-sm btn-primary" data-product data-id="{{ $product->id }}" data-name="{{ $product->name }}" data-price="{{ $product->sale_price_cents }}" data-stock="{{ $product->store_quantity }}">+</button></td></tr>@endforeach</tbody></table></div></div></div></div>
@if($sale) @include('store.receipt-modal', ['sale' => $sale, 'clinic' => $clinic])<script>document.addEventListener('DOMContentLoaded',()=>new bootstrap.Modal(document.getElementById('receiptModal{{ $sale->id }}')).show());</script>@endif
@endsection
